spring:
 datasource:
  hikari:
   maximum-pool-size: 1
 jpa:
  generate-ddl: true
  properties:
   hibernate:
    format_sql: true
    highlight_sql: true
    use_sql_comments: true
    ddl-auto: none
    show-sql: true
