spring:
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  # DB Settings
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    show-sql: true